In [39]:
import pandas as pd

# Sales Analysis

In [40]:
df = pd.read_csv("Superstore.csv", encoding="latin-1")
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [41]:
df.Sales.sum()

np.float64(2297200.8603)

In [42]:
g = df.groupby("Region")["Sales"]

for region, region_df in g:
    print(region)
    print(region_df)

Central
14       68.8100
15        2.5440
16      665.8800
21       19.4600
22       60.3400
          ...
9961     65.5840
9962    383.4656
9972     99.5680
9982     35.5600
9983     97.9800
Name: Sales, Length: 2323, dtype: float64
East
23        71.372
27      3083.430
28         9.618
29       124.200
30         3.264
          ...
9968     735.980
9969      22.750
9981      16.520
9984      31.500
9985      55.600
Name: Sales, Length: 2848, dtype: float64
South
0       261.9600
1       731.9400
3       957.5775
4        22.3680
12       15.5520
          ...
9971    140.7500
9980     85.9800
9987     79.9900
9988    206.1000
9989     25.2480
Name: Sales, Length: 1620, dtype: float64
West
2        14.620
5        48.860
6         7.280
7       907.152
8        18.504
         ...
9986     36.240
9990     91.960
9991    258.576
9992     29.600
9993    243.160
Name: Sales, Length: 3203, dtype: float64

In [43]:
g.sum().sort_values(ascending=True)

Region
South      391721.9050
Central    501239.8908
East       678781.2400
West       725457.8245
Name: Sales, dtype: float64

The highest number of total sales took place in the West region which is 725457.8245 and least number of total sales took place in the South

In [44]:
g1 = df.groupby("Category")["Sales"]
g1.sum().sort_values(ascending=True)

Category
Office Supplies    719047.0320
Furniture          741999.7953
Technology         836154.0330
Name: Sales, dtype: float64

So the highest number of sales occured in the "Technology" category which were 836154.0330 and least number of sales occured in the "Office Supplies" category

In [45]:
print(df.Category.unique())

g2 = df[df["Category"] == "Furniture"].groupby("Sub-Category")["Sales"]
print(g2.sum().sort_values(ascending=True))

print("\n")

g3 = df[df["Category"] == "Office Supplies"].groupby("Sub-Category")["Sales"]
print(g3.sum().sort_values(ascending=True))

print("\n")

g4 = df[df["Category"] == "Technology"].groupby("Sub-Category")["Sales"]
print(g4.sum().sort_values(ascending=True))

<StringArray>
['Furniture', 'Office Supplies', 'Technology']
Length: 3, dtype: str
Sub-Category
Furnishings     91705.1640
Bookcases      114879.9963
Tables         206965.5320
Chairs         328449.1030
Name: Sales, dtype: float64


Sub-Category
Fasteners       3024.280
Labels         12486.312
Envelopes      16476.402
Art            27118.792
Supplies       46673.538
Paper          78479.206
Appliances    107532.161
Binders       203412.733
Storage       223843.608
Name: Sales, dtype: float64


Sub-Category
Copiers        149528.030
Accessories    167380.318
Machines       189238.631
Phones         330007.054
Name: Sales, dtype: float64

In the,

-> Furniture Category, the highest number of total sales were made by "Chairs" which is 328449.1030

-> Office Supplies Category, the highest number of total sales were made by "Storage" which is 223843.608

-> Technology Category, the highest number of total sales were made by "Phones" which is 330007.054

In [46]:
df["Order Date"] = pd.to_datetime(df["Order Date"])
df["Year"] = df["Order Date"].dt.year
df["Month"] = df["Order Date"].dt.month

# Profit Analysis

In [ ]:
df["Profit"].sum()

np.float64(442528.3074)

Total profit made is 286397.0217

In [80]:
grp1 = df.groupby("Category")["Profit"]
grp1.sum().sort_values(ascending=True)

Category
Furniture           18451.2728
Office Supplies    122490.8008
Technology         145454.9481
Name: Profit, dtype: float64

The higest profit is made by the "Technology" Category which is 145454.9481 and least proft was made by "Furniture" Category which is 18451.2728

In [72]:
profit_region = df[df["Region"] == "Central"].groupby("Profit")

for i, i_df in profit_region:
    print(i)
    print(i_df)

-3701.8928
      Row ID        Order ID Order Date  Ship Date       Ship Mode  \
9774    9775  CA-2014-169019 2014-07-26  7/30/2014  Standard Class

     Customer ID Customer Name   Segment        Country         City  ...  \
9774    LF-17185   Luke Foster  Consumer  United States  San Antonio  ...

           Product ID         Category Sub-Category  \
9774  OFF-BI-10004995  Office Supplies      Binders

                                   Product Name     Sales Quantity Discount  \
9774  GBC DocuBind P400 Electric Binding System  2177.584        8      0.8

         Profit  Year  Month
9774 -3701.8928  2014      7

[1 rows x 23 columns]
-2929.4845
      Row ID        Order ID Order Date   Ship Date       Ship Mode  \
4991    4992  US-2017-122714 2017-12-07  12/13/2017  Standard Class

     Customer ID  Customer Name    Segment        Country     City  ...  \
4991    HG-14965  Henry Goldwyn  Corporate  United States  Chicago  ...

           Product ID         Category Sub-Category  \
4991  OFF-BI-10001120  Office Supplies      Binders

                              Product Name    Sales Quantity Discount  \
4991  Ibico EPK-21 Electric Binding System  1889.99        5      0.8

         Profit  Year  Month
4991 -2929.4845  2017     12

[1 rows x 23 columns]
-2287.782
      Row ID        Order ID Order Date   Ship Date    Ship Mode Customer ID  \
5310    5311  CA-2017-131254 2017-11-19  11/21/2017  First Class    NC-18415

     Customer Name   Segment        Country     City  ...       Product ID  \
5310   Nathan Cano  Consumer  United States  Houston  ...  OFF-BI-10003527

             Category Sub-Category  \
5310  Office Supplies      Binders

                                           Product Name     Sales Quantity  \
5310  Fellowes PB500 Electric Punch Plastic Comb Bin...  1525.188        6

     Discount    Profit  Year  Month
5310      0.8 -2287.782  2017     11

[1 rows x 23 columns]
-1850.9464
      Row ID        Order ID Order Date  Ship Date       Ship Mode  \
1199    1200  CA-2016-130946 2016-04-08  4/12/2016  Standard Class

     Customer ID     Customer Name   Segment        Country     City  ...  \
1199    ZC-21910  Zuschuss Carroll  Consumer  United States  Houston  ...

           Product ID         Category Sub-Category  \
1199  OFF-BI-10004995  Office Supplies      Binders

                                   Product Name     Sales Quantity Discount  \
1199  GBC DocuBind P400 Electric Binding System  1088.792        4      0.8

         Profit  Year  Month
1199 -1850.9464  2016      4

[1 rows x 23 columns]
-1480.0335
      Row ID        Order ID Order Date   Ship Date       Ship Mode  \
3324    3325  CA-2014-165309 2014-11-11  11/15/2014  Standard Class

     Customer ID  Customer Name   Segment        Country     City  ...  \
3324    KD-16270  Karen Daniels  Consumer  United States  Houston  ...

           Product ID         Category Sub-Category  \
3324  OFF-BI-10001359  Office Supplies      Binders

                                    Product Name   Sales Quantity Discount  \
3324  GBC DocuBind TL300 Electric Binding System  896.99        5      0.8

         Profit  Year  Month
3324 -1480.0335  2014     11

[1 rows x 23 columns]
-1359.992
     Row ID        Order ID Order Date  Ship Date       Ship Mode Customer ID  \
165     166  CA-2014-139892 2014-09-08  9/12/2014  Standard Class    BM-11140

    Customer Name   Segment        Country         City  ...       Product ID  \
165  Becky Martin  Consumer  United States  San Antonio  ...  TEC-MA-10000822

       Category Sub-Category                               Product Name  \
165  Technology     Machines  Lexmark MX611dhe Monochrome Laser Printer

        Sales Quantity Discount    Profit  Year  Month
165  8159.952        8      0.4 -1359.992  2014      9

[1 rows x 23 columns]
-1181.2824
      Row ID        Order ID Order Date  Ship Date       Ship Mode  \
4820    4821  CA-2015-140025 2015-04-07  4/11/2015  Standard Class

     Customer ID Customer Name   Segment        Country         City  ...  \
4820    PF-19120  Peter Fuller  Consumer  United States  San Antonio  ...

           Product ID         Category Sub-Category  \
4820  OFF-AP-10002651  Office Supplies   Appliances

                             Product Name    Sales Quantity Discount  \
4820  Hoover Upright Vacuum With Dirt Cup  463.248        8      0.8

         Profit  Year  Month
4820 -1181.2824  2015      4

[1 rows x 23 columns]
-1143.891
      Row ID        Order ID Order Date  Ship Date       Ship Mode  \
2846    2847  CA-2017-152093 2017-09-10  9/15/2017  Standard Class

     Customer ID Customer Name      Segment        Country     City  ...  \
2846    SN-20560  Skye Norling  Home Office  United States  Chicago  ...

           Product ID         Category Sub-Category  \
2846  OFF-BI-10003527  Office Supplies      Binders

                                           Product Name    Sales Quantity  \
2846  Fellowes PB500 Electric Punch Plastic Comb Bin...  762.594        3

     Discount    Profit  Year  Month
2846      0.8 -1143.891  2017      9

[1 rows x 23 columns]
-1141.47
      Row ID        Order ID Order Date  Ship Date       Ship Mode  \
8640    8641  US-2017-148551 2017-01-12  1/16/2017  Standard Class

     Customer ID Customer Name    Segment        Country    City  ...  \
8640    DB-13120  David Bremer  Corporate  United States  Dallas  ...

           Product ID         Category Sub-Category  \
8640  OFF-BI-10000545  Office Supplies      Binders

                                          Product Name   Sales Quantity  \
8640  GBC Ibimaster 500 Manual ProClick Binding System  760.98        5

     Discount   Profit  Year  Month
8640      0.8 -1141.47  2017      1

[1 rows x 23 columns]
-786.0144
      Row ID        Order ID Order Date Ship Date       Ship Mode Customer ID  \
5198    5199  CA-2016-103982 2016-03-03  3/8/2016  Standard Class    AA-10315

     Customer Name   Segment        Country        City  ...       Product ID  \
5198    Alex Avila  Consumer  United States  Round Rock  ...  OFF-SU-10000151

             Category Sub-Category  \
5198  Office Supplies     Supplies

                                     Product Name     Sales Quantity Discount  \
5198  High Speed Automatic Electric Letter Opener  3930.072        3      0.2

        Profit  Year  Month
5198 -786.0144  2016      3

[1 rows x 23 columns]
-766.012
      Row ID        Order ID Order Date  Ship Date     Ship Mode Customer ID  \
1995    1996  US-2017-147221 2017-12-02  12/4/2017  Second Class    JS-16030

     Customer Name   Segment        Country     City  ...       Product ID  \
1995     Joy Smith  Consumer  United States  Houston  ...  OFF-AP-10002534

             Category Sub-Category  \
1995  Office Supplies   Appliances

                                           Product Name   Sales Quantity  \
1995  3.6 Cubic Foot Counter Height Office Refrigerator  294.62        5

     Discount   Profit  Year  Month
1995      0.8 -766.012  2017     12

[1 rows x 23 columns]
-729.9138
      Row ID        Order ID Order Date  Ship Date    Ship Mode Customer ID  \
6262    6263  CA-2016-132479 2016-09-24  9/26/2016  First Class    MK-17905

        Customer Name    Segment        Country      City  ...  \
6262  Michael Kennedy  Corporate  United States  Rockford  ...

           Product ID         Category Sub-Category  \
6262  OFF-BI-10004584  Office Supplies      Binders

                                      Product Name    Sales Quantity Discount  \
6262  GBC ProClick 150 Presentation Binding System  442.372        7      0.8

        Profit  Year  Month
6262 -729.9138  2016      9

[1 rows x 23 columns]
-566.5625
      Row ID        Order ID Order Date  Ship Date     Ship Mode Customer ID  \
1713    1714  US-2017-124968 2017-09-08  9/13/2017  Second Class    MM-18055

       Customer Name   Segment        Country     City  ...       Product ID  \
1713  Michelle Moray  Consumer  United States  Chicago  ...  FUR-TA-10004289

       Category Sub-Category  \
1713  Furniture       Tables

                                           Product Name    Sales Quantity  \
1713  BoxOffice By Design Rectangular and Half-Moon ...  765.625        7

     Discount    Profit  Year  Month
1713      0.5 -566.5625  2017      9

[1 rows x 23 columns]
-538.446
      Row ID        Order ID Order Date Ship Date       Ship Mode Customer ID  \
8926    8927  CA-2016-168032 2016-01-30  2/3/2016  Standard Class    DF-13135

       Customer Name   Segment        Country      City  ...       Product ID  \
8926  David Flashing  Consumer  United States  Rockford  ...  FUR-TA-10004256

       Category Sub-Category  \
8926  Furniture       Tables

                                           Product Name  Sales Quantity  \
8926  Bretford Just In Time Height-Adjustable Mult...  626.1        3

     Discount   Profit  Year  Month
8926      0.5 -538.446  2016      1

[1 rows x 23 columns]
-533.7325
      Row ID        Order ID Order Date  Ship Date       Ship Mode  \
9480    9481  CA-2014-126193 2014-09-07  9/14/2014  Standard Class

     Customer ID    Customer Name   Segment        Country    City  ...  \
9480    SS-20410  Shahid Shariari  Consumer  United States  Oswego  ...

           Product ID         Category Sub-Category  \
9480  OFF-BI-10004632  Office Supplies      Binders

                             Product Name   Sales Quantity Discount    Profit  \
9480  Ibico Hi-Tech Manual Binding System  304.99        5      0.8 -533.7325

      Year  Month
9480  2014      9

[1 rows x 23 columns]
-525.6405
      Row ID        Order ID Order Date  Ship Date    Ship Mode Customer ID  \
3519    3520  CA-2015-124975 2015-06-22  6/25/2015  First Class    MG-17875

      Customer Name      Segment        Country    City  ...       Product ID  \
3519  Michael Grace  Home Office  United States  Aurora  ...  FUR-TA-10002645

       Category Sub-Category                       Product Name    Sales  \
3519  Furniture       Tables  Hon Rectangular Conference Tables  796.425

     Quantity Discount    Profit  Year  Month
3519        7      0.5 -525.6405  2015      6

[1 rows x 23 columns]
-512.1468
      Row ID        Order ID Order Date  Ship Date       Ship Mode  \
6035    6036  US-2015-155369 2015-04-19  4/25/2015  Standard Class

     Customer ID    Customer Name   Segment        Country        City  ...  \
6035    PG-18820  Patrick Gardner  Consumer  United States  Carrollton  ...

           Product ID         Category Sub-Category  \
6035  OFF-BI-10003925  Office Supplies      Binders

                                     Product Name    Sales Quantity Discount  \
6035  Fellowes PB300 Plastic Comb Binding Machine  310.392        4      0.8

        Profit  Year  Month
6035 -512.1468  2015      4

[1 rows x 23 columns]
-509.997
     Row ID        Order ID Order Date  Ship Date     Ship Mode Customer ID  \
262     263  US-2014-106992 2014-09-19  9/21/2014  Second Class    SB-20290

    Customer Name    Segment        Country     City  ...       Product ID  \
262  Sean Braxton  Corporate  United States  Houston  ...  TEC-MA-10000822

       Category Sub-Category                               Product Name  \
262  Technology     Machines  Lexmark MX611dhe Monochrome Laser Printer

        Sales Quantity Discount   Profit  Year  Month
262  3059.982        3      0.4 -509.997  2014      9

[1 rows x 23 columns]
-470.548
      Row ID        Order ID Order Date Ship Date     Ship Mode Customer ID  \
8251    8252  CA-2015-140221 2015-03-05  3/9/2015  Second Class    MS-17365

            Customer Name   Segment        Country     City  ...  \
8251  Maribeth Schnelling  Consumer  United States  Chicago  ...

           Product ID         Category Sub-Category  \
8251  OFF-AP-10000828  Office Supplies   Appliances

                         Product Name   Sales Quantity Discount   Profit  \
8251  Avanti 4.4 Cu. Ft. Refrigerator  180.98        5      0.8 -470.548

      Year  Month
8251  2015      3

[1 rows x 23 columns]
-459.6072
      Row ID        Order ID Order Date Ship Date       Ship Mode Customer ID  \
7348    7349  CA-2014-130421 2014-03-03  3/7/2014  Standard Class    SC-20020

     Customer Name   Segment        Country     City  ...       Product ID  \
7348    Sam Craven  Consumer  United States  Houston  ...  OFF-AP-10002534

             Category Sub-Category  \
7348  Office Supplies   Appliances

                                           Product Name    Sales Quantity  \
7348  3.6 Cubic Foot Counter Height Office Refrigerator  176.772        3

     Discount    Profit  Year  Month
7348      0.8 -459.6072  2014      3

[1 rows x 23 columns]
-453.849
     Row ID        Order ID Order Date  Ship Date       Ship Mode Customer ID  \
169     170  CA-2014-139892 2014-09-08  9/12/2014  Standard Class    BM-11140

    Customer Name   Segment        Country         City  ...       Product ID  \
169  Becky Martin  Consumer  United States  San Antonio  ...  OFF-AP-10002518

            Category Sub-Category  \
169  Office Supplies   Appliances

                                     Product Name   Sales Quantity Discount  \
169  Kensington 7 Outlet MasterPiece Power Center  177.98        5      0.8

      Profit  Year  Month
169 -453.849  2014      9

[1 rows x 23 columns]
-437.5404
      Row ID        Order ID Order Date Ship Date     Ship Mode Customer ID  \
5055    5056  CA-2015-141243 2015-01-03  1/8/2015  Second Class    AH-10465

     Customer Name   Segment        Country    City  ...       Product ID  \
5055      Amy Hunt  Consumer  United States  Dallas  ...  FUR-BO-10003272

       Category Sub-Category                                    Product Name  \
5055  Furniture    Bookcases  O'Sullivan Living Dimensions 5-Shelf Bookcases

          Sales Quantity Discount    Profit  Year  Month
5055  1352.3976        9     0.32 -437.5404  2015      1

[1 rows x 23 columns]
-430.617
      Row ID        Order ID Order Date   Ship Date       Ship Mode  \
1394    1395  US-2017-117247 2017-10-09  10/14/2017  Standard Class

     Customer ID Customer Name    Segment        Country    City  ...  \
1394    CK-12760   Cyma Kinney  Corporate  United States  Aurora  ...

           Product ID   Category Sub-Category  \
1394  FUR-TA-10002958  Furniture       Tables

                             Product Name   Sales Quantity Discount   Profit  \
1394  Bevis Oval Conference Table, Walnut  652.45        5      0.5 -430.617

      Year  Month
1394  2017     10

[1 rows x 23 columns]
-427.45
      Row ID        Order ID Order Date   Ship Date     Ship Mode Customer ID  \
3316    3317  CA-2017-161739 2017-11-10  11/15/2017  Second Class    EB-13750

      Customer Name    Segment        Country        City  ...  \
3316  Edward Becker  Corporate  United States  Round Rock  ...

           Product ID   Category Sub-Category  \
3316  FUR-FU-10001468  Furniture  Furnishings

                              Product Name   Sales Quantity Discount  Profit  \
3316  Tenex Antistatic Computer Chair Mats  341.96        5      0.6 -427.45

      Year  Month
3316  2017     11

[1 rows x 23 columns]
-426.986
      Row ID        Order ID Order Date Ship Date     Ship Mode Customer ID  \
6566    6567  CA-2017-131282 2017-02-05  2/8/2017  Second Class    CB-12025

          Customer Name   Segment        Country  City  ...       Product ID  \
6566  Cassandra Brandow  Consumer  United States  Waco  ...  OFF-BI-10004632

             Category Sub-Category                         Product Name  \
6566  Office Supplies      Binders  Ibico Hi-Tech Manual Binding System

        Sales Quantity Discount   Profit  Year  Month
6566  243.992        4      0.8 -426.986  2017      2

[1 rows x 23 columns]
-417.0936
      Row ID        Order ID Order Date  Ship Date       Ship Mode  \
3084    3085  CA-2017-118773 2017-02-09  2/14/2017  Standard Class

     Customer ID Customer Name   Segment        Country     City  ...  \
3084    TP-21415  Tom Prescott  Consumer  United States  Houston  ...

           Product ID         Category Sub-Category  \
3084  OFF-BI-10004584  Office Supplies      Binders

                                      Product Name    Sales Quantity Discount  \
3084  GBC ProClick 150 Presentation Binding System  252.784        4      0.8

        Profit  Year  Month
3084 -417.0936  2017      2

[1 rows x 23 columns]
-407.682
     Row ID        Order ID Order Date  Ship Date       Ship Mode Customer ID  \
125     126  US-2014-134614 2014-09-20  9/25/2014  Standard Class    PF-19165

    Customer Name   Segment        Country         City  ...       Product ID  \
125    Philip Fox  Consumer  United States  Bloomington  ...  FUR-TA-10004534

      Category Sub-Category                     Product Name  Sales Quantity  \
125  Furniture       Tables  Bevis 44 x 96 Conference Tables  617.7        6

    Discount   Profit  Year  Month
125      0.5 -407.682  2014      9

[1 rows x 23 columns]
-393.602
      Row ID        Order ID Order Date  Ship Date       Ship Mode  \
9164    9165  CA-2015-164007 2015-06-08  6/12/2015  Standard Class

     Customer ID  Customer Name   Segment        Country     City  ...  \
9164    MG-17695  Maureen Gnade  Consumer  United States  Chicago  ...

           Product ID         Category Sub-Category  \
9164  OFF-AP-10003849  Office Supplies   Appliances

                                        Product Name    Sales Quantity  \
9164  Hoover Shoulder Vac Commercial Portable Vacuum  143.128        2

     Discount   Profit  Year  Month
9164      0.8 -393.602  2015      6

[1 rows x 23 columns]
-378.4
      Row ID        Order ID Order Date Ship Date       Ship Mode Customer ID  \
9592    9593  US-2016-105452 2016-07-28  8/1/2016  Standard Class    BF-11005

     Customer Name      Segment        Country      City  ...  \
9592   Barry Franz  Home Office  United States  Pasadena  ...

           Product ID   Category Sub-Category  \
9592  FUR-FU-10003806  Furniture  Furnishings

                                  Product Name   Sales Quantity Discount  \
9592  Tenex Chairmat w/ Average Lip, 45" x 53"  302.72        5      0.6

      Profit  Year  Month
9592  -378.4  2016      7

[1 rows x 23 columns]
-356.728
     Row ID        Order ID Order Date Ship Date     Ship Mode Customer ID  \
238     239  CA-2016-157749 2016-06-04  6/9/2016  Second Class    KL-16645

    Customer Name   Segment        Country     City  ...       Product ID  \
238  Ken Lonsdale  Consumer  United States  Chicago  ...  FUR-FU-10000576

      Category Sub-Category  \
238  Furniture  Furnishings

                                          Product Name   Sales Quantity  \
238  Luxo Professional Fluorescent Magnifier Lamp w...  419.68        5

    Discount   Profit  Year  Month
238      0.6 -356.728  2016      6

[1 rows x 23 columns]
-350.49
      Row ID        Order ID Order Date   Ship Date Ship Mode Customer ID  \
1438    1439  CA-2015-139731 2015-10-15  10/15/2015  Same Day    JE-15745

     Customer Name   Segment        Country      City  ...       Product ID  \
1438    Joel Eaton  Consumer  United States  Amarillo  ...  FUR-CH-10002024

       Category Sub-Category                                  Product Name  \
1438  Furniture       Chairs  HON 5400 Series Task Chairs for Big and Tall

        Sales Quantity Discount  Profit  Year  Month
1438  2453.43        5      0.3 -350.49  2015     10

[1 rows x 23 columns]
-348.6294
      Row ID        Order ID Order Date  Ship Date       Ship Mode  \
4229    4230  CA-2017-100223 2017-07-05  7/10/2017  Standard Class

     Customer ID     Customer Name    Segment        Country    City  ...  \
4229    LS-16945  Linda Southworth  Corporate  United States  Dallas  ...

           Product ID   Category Sub-Category  \
4229  FUR-FU-10003601  Furniture  Furnishings

                                           Product Name    Sales Quantity  \
4229  Deflect-o RollaMat Studded, Beveled Mat for Me...  332.028        9


In [84]:
discount_profit = df.groupby("Discount")["Profit"]
discount_profit.mean().sort_values(ascending=True)

Discount
0.50   -310.703456
0.45   -226.646464
0.40   -111.927429
0.80   -101.796797
0.70    -95.874060
0.32    -88.560656
0.30    -45.679636
0.60    -43.077212
0.20     24.702572
0.15     27.288298
0.00     66.900292
0.10     96.055074
Name: Profit, dtype: float64

According to the data a discount of 50% account for the highest loss

We start losing from a discount of 40%

In [89]:
consumer_sales = df.groupby("Customer Name")["Sales"]
consumer_sales.max().sort_values(ascending=False).head(10)

Customer Name
Sean Miller           22638.480
Tamara Chand          17499.950
Raymond Buch          13999.960
Tom Ashbrook          11199.968
Hunter Lopez          10499.970
Adrian Barton          9892.740
Sanjit Chand           9449.950
Bill Shonely           9099.930
Sanjit Engle           8749.950
Christopher Conant     8399.976
Name: Sales, dtype: float64

Top 10 consumers
1. Sean Miller
2. Tamara Chand  
3. Raymond Buch 
4. Tom Ashbrook 
5. Hunter Lopez
6. Adrian Barton          
7. Sanjit Chand           
8. Bill Shonely           
9. Sanjit Engle           
10. Christopher Conant

In [92]:
region_profit = df.groupby("Region")["Profit"]
region_profit.sum()

Region
Central     39706.3625
East        91522.7800
South       46749.4303
West       108418.4489
Name: Profit, dtype: float64

The highest number of profit in sales was made in the West region with a profit of 108418.4489.

The least number of profit in sales was made in the Central region with a profit of 39706.3625.

In [97]:
product_analysis = df.groupby("Product Name")["Profit"]
product_analysis.sum().sort_values(ascending=False)

Product Name
Canon imageCLASS 2200 Advanced Copier                                          25199.9280
Fellowes PB500 Electric Punch Plastic Comb Binding Machine with Manual Bind     7753.0390
Hewlett Packard LaserJet 3310 Copier                                            6983.8836
Canon PC1060 Personal Laser Copier                                              4570.9347
HP Designjet T520 Inkjet Large Format Printer - 24" Color                       4094.9766
                                                                                  ...
Bush Advantage Collection Racetrack Conference Table                           -1934.3976
Chromcraft Bull-Nose Wood Oval Conference Tables & Bases                       -2876.1156
Cubify CubeX 3D Printer Triple Head Print                                      -3839.9904
Lexmark MX611dhe Monochrome Laser Printer                                      -4589.9730
Cubify CubeX 3D Printer Double Head Print                                      -8879.9704
Name: Profit, Length: 1850, dtype: float64

The highest profit is made by Canon imageCLASS 2200 Advanced Copier  which is 25199.9280.

The highest loss is made by Cubify CubeX 3D Printer Double Head Print which is -8879.9704

In [100]:
df[["Sales", "Profit", "Discount"]].corr()

             Sales    Profit  Discount
Sales     1.000000  0.479064 -0.028190
Profit    0.479064  1.000000 -0.219487
Discount -0.028190 -0.219487  1.000000

-> Highest sales then highest profits usually

-> More discount then less profits are made